# ==========================================
#  Blueprint для Telegram Autobuy Bot (v3 - Corrected)
#  С использованием внешней базы данных Neon.tech
# ==========================================

services:
  # ------------------------------------------
  #  Сервис 1: Веб-сервис для Telegram Бота
  # ------------------------------------------
  - type: web
    name: autobuy-bot-server
    env: python
    region: frankfurt 
    plan: free 
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot_server.py"
    envVars:
      # Все переменные будут взяты из панели управления Render
      # Обратите внимание, что SERVER_URL здесь больше не нужен.
      # Мы будем использовать RENDER_EXTERNAL_URL, которую Render добавит автоматически.
      - key: DATABASE_URL
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_USER_ID
        sync: false
      - key: NOTIFICATION_CHANNEL_ID
        sync: false

  # ------------------------------------------
  #  Сервис 2: Фоновый воркер для Клиент-аккаунта
  # ------------------------------------------
  - type: worker
    name: user-gift-monitor
    env: python
    region: frankfurt
    plan: starter # Важно: для воркера 24/7 нужен платный план
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python user_worker.py"
    envVars:
      # Переменные для воркера остаются без изменений
      - key: DATABASE_URL
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: SESSION_NAME
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_USER_ID
        sync: false
      - key: NOTIFICATION_CHANNEL_ID
        sync: false
